// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LRMS.Web.IntegrationTests.ApiClient.Models
{
    /// <summary>
    /// Ответ на запрос получения броней книг
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetBookReservationsResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Брони книг.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::LRMS.Web.IntegrationTests.ApiClient.Models.BookReservationDto>? BookReservations { get; set; }
#nullable restore
#else
        public List<global::LRMS.Web.IntegrationTests.ApiClient.Models.BookReservationDto> BookReservations { get; set; }
#endif
        /// <summary>Номер страницы.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? PageNumber { get; set; }
#nullable restore
#else
        public UntypedNode PageNumber { get; set; }
#endif
        /// <summary>Количество сущностей на странице.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? PageSize { get; set; }
#nullable restore
#else
        public UntypedNode PageSize { get; set; }
#endif
        /// <summary>Общее количество сущностей.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? TotalEntries { get; set; }
#nullable restore
#else
        public UntypedNode TotalEntries { get; set; }
#endif
        /// <summary>Общее количество страниц.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? TotalPages { get; set; }
#nullable restore
#else
        public UntypedNode TotalPages { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.GetBookReservationsResponse"/> and sets the default values.
        /// </summary>
        public GetBookReservationsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.GetBookReservationsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LRMS.Web.IntegrationTests.ApiClient.Models.GetBookReservationsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LRMS.Web.IntegrationTests.ApiClient.Models.GetBookReservationsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bookReservations", n => { BookReservations = n.GetCollectionOfObjectValues<global::LRMS.Web.IntegrationTests.ApiClient.Models.BookReservationDto>(global::LRMS.Web.IntegrationTests.ApiClient.Models.BookReservationDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pageNumber", n => { PageNumber = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "pageSize", n => { PageSize = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "totalEntries", n => { TotalEntries = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "totalPages", n => { TotalPages = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::LRMS.Web.IntegrationTests.ApiClient.Models.BookReservationDto>("bookReservations", BookReservations);
            writer.WriteObjectValue<UntypedNode>("pageNumber", PageNumber);
            writer.WriteObjectValue<UntypedNode>("pageSize", PageSize);
            writer.WriteObjectValue<UntypedNode>("totalEntries", TotalEntries);
            writer.WriteObjectValue<UntypedNode>("totalPages", TotalPages);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
