// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LRMS.Web.IntegrationTests.ApiClient.Models
{
    /// <summary>
    /// Состояние пространства.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SpaceStateDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Текущий трек.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LRMS.Web.IntegrationTests.ApiClient.Models.CurrentTrackDto? CurrentTrack { get; set; }
#nullable restore
#else
        public global::LRMS.Web.IntegrationTests.ApiClient.Models.CurrentTrackDto CurrentTrack { get; set; }
#endif
        /// <summary>Описание от администратора.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Уровень шума.</summary>
        public int? NoiseLevel { get; set; }
        /// <summary>Уровень загруженности в процентах.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? WorkloadLevel { get; set; }
#nullable restore
#else
        public UntypedNode WorkloadLevel { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.SpaceStateDto"/> and sets the default values.
        /// </summary>
        public SpaceStateDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.SpaceStateDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LRMS.Web.IntegrationTests.ApiClient.Models.SpaceStateDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LRMS.Web.IntegrationTests.ApiClient.Models.SpaceStateDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentTrack", n => { CurrentTrack = n.GetObjectValue<global::LRMS.Web.IntegrationTests.ApiClient.Models.CurrentTrackDto>(global::LRMS.Web.IntegrationTests.ApiClient.Models.CurrentTrackDto.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "noiseLevel", n => { NoiseLevel = n.GetIntValue(); } },
                { "workloadLevel", n => { WorkloadLevel = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::LRMS.Web.IntegrationTests.ApiClient.Models.CurrentTrackDto>("currentTrack", CurrentTrack);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("noiseLevel", NoiseLevel);
            writer.WriteObjectValue<UntypedNode>("workloadLevel", WorkloadLevel);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
