# Build stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Copy solution and project files
COPY . .

# Publish the API project
FROM build AS publish
RUN dotnet publish "LRMS.Web.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

# Copy published output
COPY --from=publish /app/publish .

# Set entry point
ENTRYPOINT ["dotnet", "LRMS.Web.dll"]