services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./src/LRMS.Web/DockerFile
    container_name: backend
    environment:
      - ASPNETCORE_URLS=http://+:5251
      - ConnectionStrings__LrmsDbContext=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - YandexMusicOptions__Token=${YANDEX_MUSIC_TOKEN}
      - ReservationManagerApiOptions__Address=${RESERVATION_MANAGER_ADDRESS}
      - ReservationManagerApiOptions__Token=${RESERVATION_MANAGER_TOKEN}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Admins=[{"Login":${ADMIN_LOGIN},"Password":${ADMIN_PASSWORD}}]
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "5251:5251"

volumes:
  postgres_data: