services:
  postgres:
    image: postgres:latest  # последняя версия PostgreSQL
    container_name: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: lrms
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d lrms -U test"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: DockerFile
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5251
      - ConnectionStrings__LrmsDbContext=Host=postgres;Port=5432;Database=lrms;Username=test;Password=test
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "5251:5251"

volumes:
  postgres_data: