// <auto-generated/>
#pragma warning disable CS0618
using LRMS.Web.IntegrationTests.ApiClient.Models;
using LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LRMS.Web.IntegrationTests.ApiClient.ReservationRequests
{
    /// <summary>
    /// Builds and executes requests for operations under \reservation-requests
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReservationRequestsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the LRMS.Web.IntegrationTests.ApiClient.reservationRequests.item collection</summary>
        /// <param name="position">Идентификатор заявки на бронирование.</param>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.Item.ReservationRequestsItemRequestBuilder"/></returns>
        public global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.Item.ReservationRequestsItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.Item.ReservationRequestsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the LRMS.Web.IntegrationTests.ApiClient.reservationRequests.item collection</summary>
        /// <param name="position">Идентификатор заявки на бронирование.</param>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.Item.ReservationRequestsItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.Item.ReservationRequestsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.Item.ReservationRequestsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.ReservationRequestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReservationRequestsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/reservation-requests{?createdDate*,pageNumber*,pageSize*,status*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.ReservationRequestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReservationRequestsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/reservation-requests{?createdDate*,pageNumber*,pageSize*,status*}", rawUrl)
        {
        }
        /// <summary>
        /// Возвращает список заявок на быстрое бронирование (имя + телефон) с пагинацией. Поддерживает фильтрацию по статусу.
        /// </summary>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.GetReservationRequestsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LRMS.Web.IntegrationTests.ApiClient.Models.GetReservationRequestsResponse?> GetAsync(Action<RequestConfiguration<global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.ReservationRequestsRequestBuilder.ReservationRequestsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LRMS.Web.IntegrationTests.ApiClient.Models.GetReservationRequestsResponse> GetAsync(Action<RequestConfiguration<global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.ReservationRequestsRequestBuilder.ReservationRequestsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LRMS.Web.IntegrationTests.ApiClient.Models.GetReservationRequestsResponse>(requestInfo, global::LRMS.Web.IntegrationTests.ApiClient.Models.GetReservationRequestsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Создаёт новую заявку на быстрое бронирование. Заявка создаётся в статусе pending и требует подтверждения администратором.
        /// </summary>
        /// <param name="body">Команда на создание запроса на бронирование стола.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::LRMS.Web.IntegrationTests.ApiClient.Models.CreateReservationRequestCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::LRMS.Web.IntegrationTests.ApiClient.Models.CreateReservationRequestCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Возвращает список заявок на быстрое бронирование (имя + телефон) с пагинацией. Поддерживает фильтрацию по статусу.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.ReservationRequestsRequestBuilder.ReservationRequestsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.ReservationRequestsRequestBuilder.ReservationRequestsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Создаёт новую заявку на быстрое бронирование. Заявка создаётся в статусе pending и требует подтверждения администратором.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Команда на создание запроса на бронирование стола.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::LRMS.Web.IntegrationTests.ApiClient.Models.CreateReservationRequestCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::LRMS.Web.IntegrationTests.ApiClient.Models.CreateReservationRequestCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.ReservationRequestsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.ReservationRequestsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.ReservationRequestsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Возвращает список заявок на быстрое бронирование (имя + телефон) с пагинацией. Поддерживает фильтрацию по статусу.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReservationRequestsRequestBuilderGetQueryParameters 
        {
            /// <summary>Фильтр по дате создания заявки (YYYY-MM-DD) — возвращает заявки, созданные в указанный день.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("createdDate")]
            public string? CreatedDate { get; set; }
#nullable restore
#else
            [QueryParameter("createdDate")]
            public string CreatedDate { get; set; }
#endif
            /// <summary>Номер страницы.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pageNumber")]
            public string? PageNumber { get; set; }
#nullable restore
#else
            [QueryParameter("pageNumber")]
            public string PageNumber { get; set; }
#endif
            /// <summary>Количество записей на странице.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pageSize")]
            public string? PageSize { get; set; }
#nullable restore
#else
            [QueryParameter("pageSize")]
            public string PageSize { get; set; }
#endif
            /// <summary>Фильтр по статусу заявки.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReservationRequestsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.ReservationRequestsRequestBuilder.ReservationRequestsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReservationRequestsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
