// <auto-generated/>
#pragma warning disable CS0618
using LRMS.Web.IntegrationTests.ApiClient.Admin;
using LRMS.Web.IntegrationTests.ApiClient.BookReservations;
using LRMS.Web.IntegrationTests.ApiClient.Books;
using LRMS.Web.IntegrationTests.ApiClient.Menu;
using LRMS.Web.IntegrationTests.ApiClient.ReservationRequests;
using LRMS.Web.IntegrationTests.ApiClient.SpaceState;
using LRMS.Web.IntegrationTests.ApiClient.TableReservations;
using LRMS.Web.IntegrationTests.ApiClient.Tables;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LRMS.Web.IntegrationTests.ApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiClient : BaseRequestBuilder
    {
        /// <summary>The admin property</summary>
        public global::LRMS.Web.IntegrationTests.ApiClient.Admin.AdminRequestBuilder Admin
        {
            get => new global::LRMS.Web.IntegrationTests.ApiClient.Admin.AdminRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bookReservations property</summary>
        public global::LRMS.Web.IntegrationTests.ApiClient.BookReservations.BookReservationsRequestBuilder BookReservations
        {
            get => new global::LRMS.Web.IntegrationTests.ApiClient.BookReservations.BookReservationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The books property</summary>
        public global::LRMS.Web.IntegrationTests.ApiClient.Books.BooksRequestBuilder Books
        {
            get => new global::LRMS.Web.IntegrationTests.ApiClient.Books.BooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The menu property</summary>
        public global::LRMS.Web.IntegrationTests.ApiClient.Menu.MenuRequestBuilder Menu
        {
            get => new global::LRMS.Web.IntegrationTests.ApiClient.Menu.MenuRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reservationRequests property</summary>
        public global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.ReservationRequestsRequestBuilder ReservationRequests
        {
            get => new global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.ReservationRequestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The spaceState property</summary>
        public global::LRMS.Web.IntegrationTests.ApiClient.SpaceState.SpaceStateRequestBuilder SpaceState
        {
            get => new global::LRMS.Web.IntegrationTests.ApiClient.SpaceState.SpaceStateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tableReservations property</summary>
        public global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.TableReservationsRequestBuilder TableReservations
        {
            get => new global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.TableReservationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tables property</summary>
        public global::LRMS.Web.IntegrationTests.ApiClient.Tables.TablesRequestBuilder Tables
        {
            get => new global::LRMS.Web.IntegrationTests.ApiClient.Tables.TablesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LRMS.Web.IntegrationTests.ApiClient.ApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "http://localhost:5251";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
