// <auto-generated/>
#pragma warning disable CS0618
using LRMS.Web.IntegrationTests.ApiClient.Models;
using LRMS.Web.IntegrationTests.ApiClient.TableReservations.Item;
using LRMS.Web.IntegrationTests.ApiClient.TableReservations.Slots;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LRMS.Web.IntegrationTests.ApiClient.TableReservations
{
    /// <summary>
    /// Builds and executes requests for operations under \table-reservations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TableReservationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The slots property</summary>
        public global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.Slots.SlotsRequestBuilder Slots
        {
            get => new global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.Slots.SlotsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the LRMS.Web.IntegrationTests.ApiClient.tableReservations.item collection</summary>
        /// <param name="position">Идентификатор брони стола.</param>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.Item.TableReservationsItemRequestBuilder"/></returns>
        public global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.Item.TableReservationsItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.Item.TableReservationsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the LRMS.Web.IntegrationTests.ApiClient.tableReservations.item collection</summary>
        /// <param name="position">Идентификатор брони стола.</param>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.Item.TableReservationsItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.Item.TableReservationsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.Item.TableReservationsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.TableReservationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TableReservationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/table-reservations{?activeAt*,pageNumber*,pageSize*,tableId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.TableReservationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TableReservationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/table-reservations{?activeAt*,pageNumber*,pageSize*,tableId*}", rawUrl)
        {
        }
        /// <summary>
        /// Возвращает список бронирований столов с пагинацией.
        /// </summary>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.GetTableReservationsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LRMS.Web.IntegrationTests.ApiClient.Models.GetTableReservationsResponse?> GetAsync(Action<RequestConfiguration<global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.TableReservationsRequestBuilder.TableReservationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LRMS.Web.IntegrationTests.ApiClient.Models.GetTableReservationsResponse> GetAsync(Action<RequestConfiguration<global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.TableReservationsRequestBuilder.TableReservationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LRMS.Web.IntegrationTests.ApiClient.Models.GetTableReservationsResponse>(requestInfo, global::LRMS.Web.IntegrationTests.ApiClient.Models.GetTableReservationsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Создаёт новое бронирование стола.
        /// </summary>
        /// <param name="body">Команда создания бронирования стола.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 409 status code</exception>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::LRMS.Web.IntegrationTests.ApiClient.Models.CreateTableReservationCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::LRMS.Web.IntegrationTests.ApiClient.Models.CreateTableReservationCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "409", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Возвращает список бронирований столов с пагинацией.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.TableReservationsRequestBuilder.TableReservationsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.TableReservationsRequestBuilder.TableReservationsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Создаёт новое бронирование стола.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Команда создания бронирования стола.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::LRMS.Web.IntegrationTests.ApiClient.Models.CreateTableReservationCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::LRMS.Web.IntegrationTests.ApiClient.Models.CreateTableReservationCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.TableReservationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.TableReservationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.TableReservationsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Возвращает список бронирований столов с пагинацией.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TableReservationsRequestBuilderGetQueryParameters 
        {
            /// <summary>Фильтр по дате (UTC, ISO-8601). Принимает либо date YYYY-MM-DD — возвращает брони, активные в указанный день; либо date-time — возвращает брони, активные в указанный момент времени.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("activeAt")]
            public string? ActiveAt { get; set; }
#nullable restore
#else
            [QueryParameter("activeAt")]
            public string ActiveAt { get; set; }
#endif
            /// <summary>Номер страницы.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pageNumber")]
            public string? PageNumber { get; set; }
#nullable restore
#else
            [QueryParameter("pageNumber")]
            public string PageNumber { get; set; }
#endif
            /// <summary>Количество записей на странице.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pageSize")]
            public string? PageSize { get; set; }
#nullable restore
#else
            [QueryParameter("pageSize")]
            public string PageSize { get; set; }
#endif
            /// <summary>Фильтр по ID стола.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tableId")]
            public string? TableId { get; set; }
#nullable restore
#else
            [QueryParameter("tableId")]
            public string TableId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TableReservationsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::LRMS.Web.IntegrationTests.ApiClient.TableReservations.TableReservationsRequestBuilder.TableReservationsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TableReservationsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
