// <auto-generated/>
#pragma warning disable CS0618
using LRMS.Web.IntegrationTests.ApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \reservation-requests\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReservationRequestsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.Item.ReservationRequestsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReservationRequestsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/reservation-requests/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.Item.ReservationRequestsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReservationRequestsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/reservation-requests/{id}", rawUrl)
        {
        }
        /// <summary>
        /// Переводит заявку из статуса pending в confirmed или cancelled.
        /// </summary>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ReservationRequestDto"/></returns>
        /// <param name="body">Команда на обновление статуса заявки на бронирование стола.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 409 status code</exception>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LRMS.Web.IntegrationTests.ApiClient.Models.ReservationRequestDto?> PutAsync(global::LRMS.Web.IntegrationTests.ApiClient.Models.UpdateReservationRequestCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LRMS.Web.IntegrationTests.ApiClient.Models.ReservationRequestDto> PutAsync(global::LRMS.Web.IntegrationTests.ApiClient.Models.UpdateReservationRequestCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "409", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LRMS.Web.IntegrationTests.ApiClient.Models.ReservationRequestDto>(requestInfo, global::LRMS.Web.IntegrationTests.ApiClient.Models.ReservationRequestDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Переводит заявку из статуса pending в confirmed или cancelled.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Команда на обновление статуса заявки на бронирование стола.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::LRMS.Web.IntegrationTests.ApiClient.Models.UpdateReservationRequestCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::LRMS.Web.IntegrationTests.ApiClient.Models.UpdateReservationRequestCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.Item.ReservationRequestsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.Item.ReservationRequestsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LRMS.Web.IntegrationTests.ApiClient.ReservationRequests.Item.ReservationRequestsItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReservationRequestsItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
