// <auto-generated/>
#pragma warning disable CS0618
using LRMS.Web.IntegrationTests.ApiClient.Menu.Category.Item;
using LRMS.Web.IntegrationTests.ApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LRMS.Web.IntegrationTests.ApiClient.Menu.Category
{
    /// <summary>
    /// Builds and executes requests for operations under \menu\category
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CategoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the LRMS.Web.IntegrationTests.ApiClient.menu.category.item collection</summary>
        /// <param name="position">Идентификатор категории меню.</param>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.Menu.Category.Item.CategoryItemRequestBuilder"/></returns>
        public global::LRMS.Web.IntegrationTests.ApiClient.Menu.Category.Item.CategoryItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::LRMS.Web.IntegrationTests.ApiClient.Menu.Category.Item.CategoryItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the LRMS.Web.IntegrationTests.ApiClient.menu.category.item collection</summary>
        /// <param name="position">Идентификатор категории меню.</param>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.Menu.Category.Item.CategoryItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::LRMS.Web.IntegrationTests.ApiClient.Menu.Category.Item.CategoryItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::LRMS.Web.IntegrationTests.ApiClient.Menu.Category.Item.CategoryItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LRMS.Web.IntegrationTests.ApiClient.Menu.Category.CategoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CategoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/menu/category", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LRMS.Web.IntegrationTests.ApiClient.Menu.Category.CategoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CategoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/menu/category", rawUrl)
        {
        }
        /// <summary>
        /// Создает категорию меню с элементами.
        /// </summary>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.MenuCategoryDto"/></returns>
        /// <param name="body">Команда создания категории меню.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 422 status code</exception>
        /// <exception cref="global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LRMS.Web.IntegrationTests.ApiClient.Models.MenuCategoryDto?> PostAsync(global::LRMS.Web.IntegrationTests.ApiClient.Models.CreateMenuCategoryCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LRMS.Web.IntegrationTests.ApiClient.Models.MenuCategoryDto> PostAsync(global::LRMS.Web.IntegrationTests.ApiClient.Models.CreateMenuCategoryCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::LRMS.Web.IntegrationTests.ApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::LRMS.Web.IntegrationTests.ApiClient.Models.MenuCategoryDto>(requestInfo, global::LRMS.Web.IntegrationTests.ApiClient.Models.MenuCategoryDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Создает категорию меню с элементами.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Команда создания категории меню.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::LRMS.Web.IntegrationTests.ApiClient.Models.CreateMenuCategoryCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::LRMS.Web.IntegrationTests.ApiClient.Models.CreateMenuCategoryCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LRMS.Web.IntegrationTests.ApiClient.Menu.Category.CategoryRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LRMS.Web.IntegrationTests.ApiClient.Menu.Category.CategoryRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LRMS.Web.IntegrationTests.ApiClient.Menu.Category.CategoryRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CategoryRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
